// <auto-generated />
namespace PGD.DatabaseUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Campo_NivelAvaliacao_Em_AvaliacaoProduto : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Campo_NivelAvaliacao_Em_AvaliacaoProduto));
        
        string IMigrationMetadata.Id
        {
            get { return "201912022025146_Campo_NivelAvaliacao_Em_AvaliacaoProduto"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
