// <auto-generated />
namespace PGD.DatabaseUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Tabelas_OS_CriterioAvaliacao_OS_ItemAvaliacao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Tabelas_OS_CriterioAvaliacao_OS_ItemAvaliacao));
        
        string IMigrationMetadata.Id
        {
            get { return "201911261658575_Tabelas_OS_CriterioAvaliacao_OS_ItemAvaliacao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
