// <auto-generated />
namespace PGD.DatabaseUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Populando_Tabela_TipoPacto_Unidade : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Populando_Tabela_TipoPacto_Unidade));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251810015_Populando_Tabela_TipoPacto_Unidade"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
