// <auto-generated />
namespace PGD.DatabaseUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Incluindo_Faixa_Nota : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Incluindo_Faixa_Nota));
        
        string IMigrationMetadata.Id
        {
            get { return "201911291046379_Incluindo_Faixa_Nota"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
