// <auto-generated />
namespace PGD.DatabaseUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AlterandoCronogramaParaDouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterandoCronogramaParaDouble));
        
        string IMigrationMetadata.Id
        {
            get { return "202004031820192_AlterandoCronogramaParaDouble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
