// <auto-generated />
namespace PGD.DatabaseUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Parametro_Conclusao_Antecipada : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Parametro_Conclusao_Antecipada));
        
        string IMigrationMetadata.Id
        {
            get { return "201907251859279_Parametro_Conclusao_Antecipada"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
