// <auto-generated />
namespace PGD.DatabaseUpdate.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Ajustes_Modelo_Criterio : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Ajustes_Modelo_Criterio));
        
        string IMigrationMetadata.Id
        {
            get { return "201911261826547_Ajustes_Modelo_Criterio"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
